### ISSUE TITLE
Duplicate entry 'admin@admin.com' for key 'email_user_UNIQUE')

### ISSUE THREAD

**Issue by evogit** [mariadriada/task-project#1]
--data 'email=admin%40admin.com&passwd=1234&type=admin'

An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\Db\Adapter\Exception\InvalidQueryException
File:
/backend/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
Message:
Statement could not be executed (23000 - 1062 - Duplicate entry 'admin@admin.com' for key 'email_user_UNIQUE')
Stack trace:
#0 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#2 /backend/module/Database/src/Model/Dao/UserDao.php(49): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#3 /backend/module/Database/src/Controller/UserController.php(56): Database\Model\Dao\UserDao->save(Object(Database\Model\Entity\User))
#4 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Database\Controller\UserController->saveAction()
#5 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /backend/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /backend/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /backend/public/index.php(40): Zend\Mvc\Application->run()
#13 {main}
Previous exceptions:
PDOException
File:
/backend/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
Message:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin@admin.com' for key 'email_user_UNIQUE'
Stack trace:
#0 /backend/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#3 /backend/module/Database/src/Model/Dao/UserDao.php(49): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#4 /backend/module/Database/src/Controller/UserController.php(56): Database\Model\Dao\UserDao->save(Object(Database\Model\Entity\User))
#5 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Database\Controller\UserController->saveAction()
#6 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /backend/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /backend/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /backend/public/index.php(40): Zend\Mvc\Application->run()
#14 {main}
© 2005 - 2018 by Zend Technologies Ltd. All rights reserved.

**Comment by mariadriada** [comment]
The column: email_user in the table: user, have a UNIQUE INDEX, thus it's not possible create 2 users with the same email.
Added validation for user existing!
Please make a pull request. You need to clear browsing data (cache).
