### ISSUE TITLE
Statement could not be executed (HY000 - 1366 - Incorrect integer value: '' for column 'priority_task' at row 1)

### ISSUE THREAD

**Issue by evogit** [mariadriada/task-project#2]
--data 'id=0&name=&priority=&expiration=&idUser=5'

An error occurred
An error occurred during execution; please try again later.
Additional information:
Zend\Db\Adapter\Exception\InvalidQueryException
File:
/backend/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244
Message:
Statement could not be executed (HY000 - 1366 - Incorrect integer value: '' for column 'priority_task' at row 1)
Stack trace:
#0 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#2 /backend/module/Database/src/Model/Dao/TaskDao.php(49): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#3 /backend/module/Database/src/Controller/TaskController.php(71): Database\Model\Dao\TaskDao->save(Object(Database\Model\Entity\Task))
#4 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Database\Controller\TaskController->saveAction()
#5 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /backend/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /backend/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /backend/public/index.php(40): Zend\Mvc\Application->run()
#13 {main}
Previous exceptions:
PDOException
File:
/backend/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239
Message:
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'priority_task' at row 1
Stack trace:
#0 /backend/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(308): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /backend/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Zend\Db\TableGateway\AbstractTableGateway->executeInsert(Object(Zend\Db\Sql\Insert))
#3 /backend/module/Database/src/Model/Dao/TaskDao.php(49): Zend\Db\TableGateway\AbstractTableGateway->insert(Array)
#4 /backend/module/Database/src/Controller/TaskController.php(71): Database\Model\Dao\TaskDao->save(Object(Database\Model\Entity\Task))
#5 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Database\Controller\TaskController->saveAction()
#6 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /backend/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /backend/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#10 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /backend/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#12 /backend/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#13 /backend/public/index.php(40): Zend\Mvc\Application->run()
#14 {main}
© 2005 - 2018 by Zend Technologies Ltd. All rights reserved.

**Comment by mariadriada** [comment]
Is presented when sending empty parameters through http request.
Corrected the form required fields!
Please make a pull request. You need to clear browsing data (cache).
